version: 2.1

workflows:
  moblie-e2e-test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    # https://circleci.com/docs/ja/2.0/android-machine-image/
    machine:
      image: android:202102-01
    steps:
      - checkout
      - install-package
      - check-env
      - create-avd
      - start-emulator
      - run-appium
      - build
      - wait-boot
      - execute-test

commands:
  install-package:
    steps:
      - run:
          name: E2Eテストのために必要なパッケージをインストール
          command: |
            cd __e2e__
            npm ci

  check-env:
    steps:
      - run:
          name: E2Eテスト実行環境のチェック
          command: |
            cd __e2e__
            npm run doctor

  # https://circleci.com/docs/ja/2.0/android-machine-image/#no-orb-example
  create-avd:
    steps:
      - run:
          name: AVD の作成
          command: |
            SYSTEM_IMAGES="system-images;android-28;default;x86"
            sdkmanager "$SYSTEM_IMAGES"
            echo "no" | avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"

  start-emulator:
    steps:
      - run:
          name: エミュレーター起動
          command: |
            # 起動
            emulator -avd test -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          background: true

  run-appium:
    steps:
      - run:
          name: Appium Server の起動
          command: |
            cd __e2e__
            npm run s:appium
          background: true

  build:
    steps:
      - run:
          name: apk の Build
          # https://stackoverflow.com/questions/41700798/gradlew-command-not-found
          # https://stackoverflow.com/questions/17668265/gradlew-permission-denied
          command: |
            chmod +x gradlew
            ./gradlew assembleDebug

  wait-boot:
    steps:
      - run:
          name: エミュレーターの起動の待機
          command: |
            # エミュレーターの起動の待機
            circle-android wait-for-boot

            # エミュレーター アニメーションの無効化
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0

  execute-test:
    steps:
      - run:
          name: E2Eテスト実行
          command: |
            cd __e2e__
            npm run s:test
