version: 2.1

workflows:
  moblie-e2e-test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    # https://circleci.com/docs/ja/2.0/android-machine-image/
    machine:
      image: android:202102-01
    steps:
      - checkout

      - run:
          name: build apk
          command: gradlew assembleDebug

      - run:
          name: install for e2e test
          command: npm ci

      - run:
          name: check environment for e2e test
          command: npm run doctor
