version: 2.1

workflows:
  moblie-e2e-test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    # https://circleci.com/docs/ja/2.0/android-machine-image/
    machine:
      image: android:202102-01
    steps:
      - checkout

      - run:
          name: build apk
          # https://stackoverflow.com/questions/41700798/gradlew-command-not-found
          # https://stackoverflow.com/questions/17668265/gradlew-permission-denied
          # https://circleci.com/docs/ja/2.0/language-android/#firebase-test-lab-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%9F%E3%83%86%E3%82%B9%E3%83%88
          command: |
            pwd
            ls -al
            chmod +x (./gradlew assembleDebug)

      - run:
          name: install for e2e test
          command: |
            cd __e2e__
            npm ci

      - run:
          name: check environment for e2e test
          command: npm run doctor
